### ISSUE TITLE
T-test between FSRS and SM-17

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-vs-sm17#58]
```
Total number of users: 16
Total size: 194281

Scale: reviews
FSRSv4 LogLoss: 0.4±0.08
FSRSv4 LogLoss (mean±std): 0.370±0.101
FSRSv3 LogLoss: 0.4±0.09
FSRSv3 LogLoss (mean±std): 0.401±0.116
SM17 LogLoss: 0.4±0.10
SM17 LogLoss (mean±std): 0.414±0.121
SM16 LogLoss: 0.4±0.09
SM16 LogLoss (mean±std): 0.421±0.118

FSRSv4 RMSE(bins): 0.06±0.027
FSRSv4 RMSE(bins) (mean±std): 0.061±0.034
FSRSv3 RMSE(bins): 0.10±0.028
FSRSv3 RMSE(bins) (mean±std): 0.098±0.035
SM17 RMSE(bins): 0.10±0.039
SM17 RMSE(bins) (mean±std): 0.096±0.047
SM16 RMSE(bins): 0.12±0.027
SM16 RMSE(bins) (mean±std): 0.117±0.035
```

<img width="897" alt="image" src="https://github.com/open-spaced-repetition/fsrs-vs-sm17/assets/32575846/bc6e48ce-0e7a-4234-805d-8fb72577a0e5">

https://www.evanmiller.org/ab-testing/t-test.html

@Expertium, I find that the difference is statistically significant when we compare FSRS and SM-17 with their weighted mean and weighted standard deviation in T-test.

**Comment by Expertium** [comment]
Yeah, if we want to compare only 2 algorithms, this is the proper way. But if we have multiple algorithms, it gets complicated. And there is no nice way of representing it visually, only as an n×n table with p-values, where n is the number of algorithms.
Alright, I guess I'll do that and submit a PR later. I'll use a different test btw, not Student's t-test because I don't think we can assume normality. A quick Google search tells me that there aren't any Python libraries with a weighted version of Wilcoxon signed rank, so I'll have to carefully think of what to do. Well, worst case scenario, I guess we can use Student's t-test after all.
